### ISSUE TITLE
安装成功后, 在window/linux终端, 输入moyu后没有反应

### ISSUE THREAD

**Issue by Pan-Binghong** [PY-GZKY/Moyu_#2]
问题如图所示

Python版本为: 3.7.4 
操作系统为: windows
在cmd终端内输入`moyu`后没有响应, 在git bash终端输入`moyu`有乱码显示.
![moyu-1](https://github.com/user-attachments/assets/35672e4f-4a4a-4b36-9a24-c3248cd8bb6f)
![moyu-2](https://github.com/user-attachments/assets/dd565080-40e6-402c-a0b6-db07f540a9ef)

同时在Linux(Ubuntu22.04)服务器内, 同样安装后没有响应.

**Comment by PY-GZKY** [comment]
收到，后面改成了 moyu -up 用于实时刷新时间。

```
pip install mofish
moyu -up
```

**Comment by Pan-Binghong** [comment]
谢谢大佬~ 有显示啦
